service: api

plugins:
  - 'serverless-esbuild'
  - serverless-offline

package:
  individually: true

custom:
  stage: ${opt:stage, env:STAGE, 'dev'}
  serverless-offline:
    httpPort: 3333
    lambdaPort: 2333
    noPrependStageInUrl: true
  esbuild:
    tsconfig: 'tsconfig.app.json'

params:
  prod:
    production: true
  default:
    production: false

provider:
  name: aws
  region: ap-southeast-1
  runtime: nodejs20.x
  stage: ${self:custom.stage}
  endpointType: REGIONAL
  timeout: 20
  environment:
    APP_ENV: ${self:custom.stage}
    IS_PRODUCTION: ${param:production}
    NODE_OPTIONS: --enable-source-maps

resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:service}-customer-${sls:stage}
        BillingMode: PAY_PER_REQUEST # on-demand capacity
        AttributeDefinitions:
          - AttributeName: ID
            AttributeType: S # string
          - AttributeName: Name
            AttributeType: S # string
        KeySchema:
          - AttributeName: ID
            KeyType: HASH # partition key
          - AttributeName: Name
            KeyType: RANGE # sort key

functions:
  foo:
    handler: src/handlers/foo.lambda
    events:
      - http:
          method: GET
          path: /foo
